# Generated by Django 5.0.7 on 2024-08-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='date',
            field=models.DateField(auto_now_add=True, help_text='The date the investment was made'),
        ),
    ]
